---
- hosts: all
  tasks:
  - name: Install or ensure apache is in latest version
    yum: name=httpd state=latest
  - name: write apache config file
    template: src=/root/newhttpd.txt dest=/etc/httpd.conf
    notify:
    - restart apcahe
  - name: ensure apache is running and enabled on boot
    service:  name=httpd  state=started enabled=yes
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
